/**
 * This program creates a simple "hash" of
 * a person's name. A hash is an integer that is
 * mathematically derived from another object.
 * In this case, a string (the first and last name)
 * is accessed character by character and the hash
 * is built up from a number generated by each character.
 * While this function does not necessarily produce
 * unique hashes (different names can hash to the
 * same value), there is a relatively low possibility
 * of a "collision" with a class of roughly 400 students.
 *
 * We will learn more about hashing later this quarter!
 */

#include <iostream>
#include <cmath>
#include "console.h"
using namespace std;

int printTriangle(int layer);
int printNumTriangle(int layer);

int main() {
    int layer, ntype;
    cout << "Select the Type:";
    cin >> ntype;
    cout << "Input the layer of the Triangle:";
    cin >> layer;
    if(ntype == 1){
        printTriangle(layer);
    }
    else if(ntype == 2){
        printNumTriangle(layer);
    }
    return 0;
}


int printTriangle(int layer){
    if(layer == 0){
        layer = 6;
    }
    for(int i = layer-1; i >= 0; i--){
        for(int j = -layer; j<=layer; j++){
            int sum = abs(i) + abs(j);
            if((sum + 1)% 2 == layer % 2 && sum <= layer - 1 ){
                cout <<'*';
            }
            else{
                cout <<' ';
            }
            }
        cout<<endl;
        }

    return 0;
    }

int printNumTriangle(int layer){
    if(layer == 0){
        layer = 6;
    }
    for(int i = layer - 1; i >= 0; i--){
        for(int j = -layer; j<=layer; j++){
            int sum = abs(i) + abs(j);
            if(sum == layer - 1 ){
                cout << layer - i;
            }
            else if((sum + 1)% 2 == layer % 2 && sum <= layer - 1 && i==0 ){
                cout << layer;
            }
            else {
                cout <<' ';
            }
            }
        cout<<endl;
        }
    return 0;
    }

